module.exports = {
  'arrow-parens': [2, 'as-needed'],
  'arrow-body-style': 0,  // [2, 'as-needed'],
  'comma-dangle': [2, 'never'],
  'func-names': 0,
  'global-require': 0,
  'guard-for-in': 0,
  'no-use-before-define': [0, { functions: false }],
  'no-plusplus': 0,
  'no-param-reassign': 0,
  'no-nested-ternary': 0,
  'no-multi-assign': 0,
  'no-multi-spaces': [2, { ignoreEOLComments: true }],
  'no-multiple-empty-lines': [2, { max: 2, maxEOF: 1, maxBOF: 0 }],
  'no-unused-expressions': [2, { allowShortCircuit: true, allowTernary: true }],
  'no-mixed-operators': 0,
  'no-restricted-syntax': 0,
  'object-curly-newline': [2, { consistent: true }],
  'object-shorthand': 0,
  'operator-linebreak': [2, 'after'],
  'prefer-template': 0,
  'prefer-arrow-callback': 0,
  'prefer-rest-params': 0,
  'prefer-spread': 0,
  'prefer-destructuring': 0,
  'space-before-function-paren': [2, 'never'],
  'spaced-comment': 0,

  'import/no-dynamic-require': 0,
  'import/no-extraneous-dependencies': 0,
  'import/no-unresolved': 0,

  'jsx-a11y/href-no-hash': 0,

  'react/prop-types': 1,
  'class-methods-use-this': 0,
  'import/prefer-default-export': 0,
  'import/extensions': 0,

  'complexity': 2,
  'max-depth': 2,
  'max-lines-per-function': 2,
  'max-nested-callbacks': 2,
  'max-params': 2,
  'max-statements': 2
};
